In [1]:
def hex2bin(s):
    mp = {'0' : "0000",
          '1' : "0001",
          '2' : "0010",
          '3' : "0011",
          '4' : "0100",
          '5' : "0101",
          '6' : "0110",
          '7' : "0111",
          '8' : "1000",
          '9' : "1001",
          'A' : "1010",
          'B' : "1011",
          'C' : "1100",
          'D' : "1101",
          'E' : "1110",
          'F' : "1111" }
    bin = ""
    for i in range(len(s)):
        bin = bin + mp[s[i]]
    return bin
     
# Binary to hexadecimal conversion
def bin2hex(s):
    mp = {"0000" : '0',
          "0001" : '1',
          "0010" : '2',
          "0011" : '3',
          "0100" : '4',
          "0101" : '5',
          "0110" : '6',
          "0111" : '7',
          "1000" : '8',
          "1001" : '9',
          "1010" : 'A',
          "1011" : 'B',
          "1100" : 'C',
          "1101" : 'D',
          "1110" : 'E',
          "1111" : 'F' }
    hex = ""
    for i in range(0,len(s),4):
        ch = ""
        ch = ch + s[i]
        ch = ch + s[i + 1]
        ch = ch + s[i + 2]
        ch = ch + s[i + 3]
        hex = hex + mp[ch]
         
    return hex
 
# Binary to decimal conversion
def bin2dec(binary):
       
    binary1 = binary
    decimal, i, n = 0, 0, 0
    while(binary != 0):
        dec = binary % 10
        decimal = decimal + dec * pow(2, i)
        binary = binary//10
        i += 1
    return decimal
 
# Decimal to binary conversion
def dec2bin(num):
    res = bin(num).replace("0b", "")
    if(len(res)%4 != 0):
        div = len(res) / 4
        div = int(div)
        counter =(4 * (div + 1)) - len(res)
        for i in range(0, counter):
            res = '0' + res
    return res

# Permute function to rearrange the bits
def permute(k, arr, n):
    permutation = ""
    for i in range(0, n):
        permutation = permutation + k[arr[i] - 1]
    return permutation
 
# shifting the bits towards left by nth shifts
def shift_left(k, nth_shifts=1):
    s = ""
    for i in range(nth_shifts):
        for j in range(1,len(k)):
            s = s + k[j]
        s = s + k[0]
        k = s
        s = ""
    return k   
 
# calculating xow of two strings of binary number a and b
def xor(a, b):
    ans = ""
    for i in range(len(a)):
        if a[i] == b[i]:
            ans = ans + "0"
        else:
            ans = ans + "1"
    return ans

In [2]:
def p8_permutation(list):
    new_list = []
    new_list[0] = list[6]
    new_list[1] = list[3]
    new_list[2] = list[7]
    new_list[3] = list[4]
    new_list[4] = list[8]
    new_list[5] = list[5]
    new_list[6] = list[10]
    new_list[7] = list[9]
    
    return new_list

In [3]:
def p10_permutation(list):
    new_list = []
    new_list[0] = list[3]
    new_list[1] = list[5]
    new_list[2] = list[2]
    new_list[3] = list[7]
    new_list[4] = list[4]
    new_list[5] = list[10]
    new_list[6] = list[1]
    new_list[7] = list[9]    
    new_list[7] = list[8]
    new_list[7] = list[6]
    
    return new_list

In [8]:
import numpy as np

def table_shift(array, table_array):
    array_shifted = np.zeros(table_array.shape[0], dtype='int')
    for index, value in enumerate(table_array): array_shifted[index] = array[value - 1]
    return array_shifted

def array_split(array):
    left_split = array[:int(len(array) / 2)]
    right_split = array[int(len(array) / 2):]
    return left_split, right_split

def shifting_LtoR(array):
    temp = array[0]
    for index in range(1, len(array)): array[index - 1] = array[index]
    array[len(array) - 1] = temp
    return array

table_p_10 = np.array([3, 5, 2, 7, 4, 10, 1, 9, 8, 6])
table_p_08 = np.array([6, 3, 7, 4, 8, 5, 10, 9])

key = list('0001101101')

def split_and_merge(key):
    left_split, right_split = array_split(key)
    return np.concatenate((shifting_LtoR(left_split), shifting_LtoR(right_split)))

def key_generation_1(key, table):
    k = table_shift(key, table)
    key_merge = split_and_merge(k)
    return table_shift(key_merge, table)

def key_generation_2(key, table): return split_and_merge(key)

key_1 = key_generation_1(key, table_p_10)
print("KEY 1:", end=" ")
print("".join([str(elem) for elem in key_1]))  #1000111010

key_2 = key_generation_2(key_1, table_p_08)
print("Key 2:", end=" ")
print("".join([str(elem) for elem in key_2]))  #0001110101

KEY 1: 1000111010
Key 2: 0001110101


In [17]:
def apply_table(inp, table):
    res = ""
    for i in table:
        res += inp[i - 1]
    return res


def left_shift(data):
    return data[1:] + data[0]


def XOR(a, b):
    res = ""
    for i in range(len(a)):
        if a[i] == b[i]:
            res += "0"
        else:
            res += "1"
    return res


def apply_sbox(s, data):
    row = int("0b" + data[0] + data[-1], 2)
    col = int("0b" + data[1:3], 2)
    return bin(s[row][col])[2:]

p4_table = [2, 4, 3, 1]

def function(expansion, s0, s1, key, message):

    left = message[:4]
    right = message[4:]
    temp = apply_table(right, expansion)
    temp = XOR(temp, key)
    l = apply_sbox(s0, temp[:4])  # noqa: E741
    r = apply_sbox(s1, temp[4:])
    l = "0" * (2 - len(l)) + l  # noqa: E741
    r = "0" * (2 - len(r)) + r
    temp = apply_table(l + r, p4_table)
    temp = XOR(left, temp)
    return temp + right


def sdes(message="10101010"):

    key = key = str('0001101101')#input("Enter 10 bit key: ")
#     message = "10101010"#input("Enter 8 bit message: ")

    p8_table = [6, 3, 7, 4, 8, 5, 10, 9]
    p10_table = [3, 5, 2, 7, 4, 10, 1, 9, 8, 6]
    p4_table = [2, 4, 3, 1]
    IP = [2, 6, 3, 1, 4, 8, 5, 7]
    IP_inv = [4, 1, 3, 5, 7, 2, 8, 6]
    expansion = [4, 1, 2, 3, 2, 3, 4, 1]
    s0 = [[1, 0, 3, 2], [3, 2, 1, 0], [0, 2, 1, 3], [3, 1, 3, 2]]
    s1 = [[0, 1, 2, 3], [2, 0, 1, 3], [3, 0, 1, 0], [2, 1, 0, 3]]

    # key generation
    temp = apply_table(key, p10_table)
    left = temp[:5]
    right = temp[5:]
    left = left_shift(left)
    right = left_shift(right)
    key1 = apply_table(left + right, p8_table)
    left = left_shift(left)
    right = left_shift(right)
    left = left_shift(left)
    right = left_shift(right)
    key2 = apply_table(left + right, p8_table)

    # encryption
    temp = apply_table(message, IP)
    temp = function(expansion, s0, s1, key1, temp)
    temp = temp[4:] + temp[:4]
    temp = function(expansion, s0, s1, key2, temp)
    CT = apply_table(temp, IP_inv)
    
#     print("Cipher text is:", CT)

    # decryption
    temp = apply_table(CT, IP)
    temp = function(expansion, s0, s1, key2, temp)
    temp = temp[4:] + temp[:4]
    temp = function(expansion, s0, s1, key1, temp)
    PT = apply_table(temp, IP_inv)
#     print("Plain text after decypting is:", PT)
    
    return CT, PT
sdes(message="10101010")

('00011111', '10101010')

In [10]:
import cv2

imgGray = cv2.imread('car2.png',0)
print(imgGray.shape)
print(imgGray)

(50, 80)
[[219 223 224 ... 209 210 211]
 [225 227 226 ... 210 212 214]
 [226 224 224 ... 207 209 211]
 ...
 [ 62  65  63 ...  69  67  64]
 [ 58  61  60 ...  66  66  66]
 [ 70  71  73 ...  77  77  77]]


In [11]:
# Decimal to binary conversion
def dec2bin(num):
    res = bin(num).replace("0b", "")
    if(len(res)%4 != 0):
        div = len(res) / 4
        div = int(div)
        counter =(4 * (div + 1)) - len(res)
        for i in range(0, counter):
            res = '0' + res
    return res

# Binary to decimal conversion
def bin2dec(binary):
       
    binary1 = binary
    decimal, i, n = 0, 0, 0
    while(binary != 0):
        dec = binary % 10
        decimal = decimal + dec * pow(2, i)
        binary = binary//10
        i += 1
    return decimal

In [12]:
import numpy as np
a = np.zeros(shape=imgGray.shape)
a.shape

(50, 80)

In [18]:
for i in imgGray:
#     print(i.shape)
    for j in i:
        small_array = []
        binary_number = dec2bin(j)
        CT, PT = sdes(message = str(binary_number))
        encrypted_ct = bin2dec(int(CT))
        small_array.append(encrypted_ct)
        

IndexError: string index out of range

In [ ]:
a