In [1]:
import cv2
import numpy as np

In [4]:
list1 = []
newlist = sorted(list1, key=lambda d: d['letter']) 

In [5]:
newlist

[]

In [6]:
def create_key_list(key: str) -> list:
    key_list = []
    for letter in key:
        key_list.append({'letter': letter, 'input': []})
    return key_list

In [7]:
key_list = create_key_list('Hello')
key_list

[{'letter': 'H', 'input': []},
 {'letter': 'e', 'input': []},
 {'letter': 'l', 'input': []},
 {'letter': 'l', 'input': []},
 {'letter': 'o', 'input': []}]

In [8]:
def encrypt(img, key_list: list):
    for i in range(len(key_list)):
        for j in range(len(key_list)):
            key_list[j]['input'].append()

In [9]:
img = cv2.imread("image2.png", cv2.IMREAD_COLOR)
gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
gray_image

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 254, 254, ..., 254, 254, 255],
       [255, 254, 254, ..., 254, 254, 255],
       ...,
       [255, 255, 254, ..., 254, 255, 255],
       [255, 254, 254, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [10]:
key = 'helowrold'

In [11]:
gray_image = gray_image.ravel()

In [12]:
zeros_array = np.zeros(len(gray_image) % len(key), dtype=int)

In [13]:
zeros_array

array([], dtype=int32)

In [14]:
extended_arr = np.append(gray_image, zeros_array)

In [15]:
extended_arr

array([255, 255, 255, ..., 255, 255, 255])

In [16]:
len(extended_arr)

90000

In [17]:
extended_arr = extended_arr.reshape((int(len(extended_arr) / len(key)), len(key)))

In [18]:
extended_arr.shape

(10000, 9)

In [19]:
key_list = create_key_list(key)

In [20]:
for i in range(extended_arr.shape[1]):
    print((i))
    key_list[i]['input'] = extended_arr[:,i]

0
1
2
3
4
5
6
7
8


In [21]:
key_list = sorted(key_list, key=lambda d: d['letter']) 

In [22]:
test = key_list[0]['input'].reshape((len(key_list[0]['input']),))

In [23]:
a = np.array([key_list[0]['input']])
# a = np.append(a, test)

In [24]:
a

array([[255, 255, 238, ..., 255, 255, 255]])

In [25]:
test

array([255, 255, 238, ..., 255, 255, 255])

In [26]:
a = np.vstack((a, key_list[0]['input']))

In [27]:
a

array([[255, 255, 238, ..., 255, 255, 255],
       [255, 255, 238, ..., 255, 255, 255]])

In [45]:
final = np.array([key_list[0]['input']])
for i in range(1, len(key_list)):
    final = np.vstack((final, key_list[i]['input']))


In [46]:
final.shape

(9, 10000)

In [47]:
final.shape

(9, 10000)

In [48]:
final = final.reshape((300, 300))

In [49]:
cv2.imwrite('encrypted_ctm.jpg', final.T)

True

In [33]:
key_list

[{'letter': 'd', 'input': array([255, 255, 238, ..., 255, 255, 255])},
 {'letter': 'e', 'input': array([255, 255, 255, ..., 238, 255, 255])},
 {'letter': 'h', 'input': array([255, 255, 255, ..., 238, 255, 255])},
 {'letter': 'l', 'input': array([255, 255, 239, ..., 238, 255, 255])},
 {'letter': 'l', 'input': array([255, 255, 238, ..., 255, 255, 255])},
 {'letter': 'o', 'input': array([255, 255, 238, ..., 238, 255, 255])},
 {'letter': 'o', 'input': array([255, 255, 238, ..., 239, 255, 255])},
 {'letter': 'r', 'input': array([255, 255, 238, ..., 238, 255, 255])},
 {'letter': 'w', 'input': array([255, 255, 238, ..., 238, 255, 255])}]

In [43]:
def encrypt(img_name: str, key1, key2):
    # read the image provided
    img = cv2.imread(img_name)
    print(img)
    # Convert image to grey-scale
    # gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    # Convert to numpy array for mathematical calculations
    img = np.asarray(img)
    temp = (img * key1) % 256
    cipher = (temp + key2) % 256
    cv2.imwrite('encrypted.png',cipher)

In [44]:
encrypt('encrypted_ctm.jpg', 10, 13)

[[[255 255 255]
  [255 255 255]
  [250 250 250]
  ...
  [237 237 237]
  [253 253 253]
  [253 253 253]]

 [[254 254 254]
  [251 251 251]
  [255 255 255]
  ...
  [235 235 235]
  [255 255 255]
  [255 255 255]]

 [[238 238 238]
  [238 238 238]
  [236 236 236]
  ...
  [255 255 255]
  [234 234 234]
  [237 237 237]]

 ...

 [[254 254 254]
  [254 254 254]
  [237 237 237]
  ...
  [249 249 249]
  [255 255 255]
  [255 255 255]]

 [[253 253 253]
  [255 255 255]
  [236 236 236]
  ...
  [252 252 252]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [253 253 253]
  [239 239 239]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]]


In [51]:
img = cv2.imread("image2.png", cv2.IMREAD_COLOR)
gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imwrite('decrypt.png', gray_image)


True